### ISSUE TITLE
mount

### ISSUE THREAD

**Issue by Tortoise17** [Project-Platypus/Platypus#101]
Dear Fellows. 

I want to ask how to mount the hard disk with smb using this Platypus app? Please if you can guide. 

Cheers.

**Comment by dhadka** [comment]
Hi,

I don't think this is the correct Github project for your question.  You might be looking for https://github.com/sveinbjornt/Platypus.

**Comment by Tortoise17** [comment]
HI Yes. Thank you .. ! I close this .. So nice of you . !! Greetings.
