### ISSUE TITLE
How to get non-dominanted solutions  for two objectives optimization (NSGAII)

### ISSUE THREAD

**Issue by Abdul-2018** [Project-Platypus/Platypus#105]
I tried ti filter the solutions (algorithm.result)to get only non-dominated using 'nondominated' and 'nondominated_sort' and every time I have one of these errors:
NameError: name 'nondominated' is not defined
NameError: name 'nondominated_sort' is not defined

when I use this line of code:
nondominated_solutions = nondominated(algorithm.result)
or
nondominated_solutions = nondominated_sort(algorithm.result)

Can Anyone help me with getting non-dominanted solutions  for two objectives optimization (NSGAII)?
Thanks

**Comment by apoorvreddy** [comment]
```python
from platypus.core import nondominated_sort
```
should work ?
