### ISSUE TITLE
How to track the solutions for each generation using EpsNSGAII

### ISSUE THREAD

**Issue by tianjingyao** [Project-Platypus/Platypus#108]
I tried
"algorithm = EpsNSGAII(problem, 0.01, population_size=10)
  algorithm.run(1000)
 nondominated_solutions = nondominated(algorithm.result)"
it only returned the pareto fronts.
How could I obtain the solustion for each generation?
I have also tried the code https://github.com/Project-Platypus/Platypus/issues/71#issuecomment-513524660
but it only works for NSGAII. I don't know how to do it for EpsNSGAII

**Comment by pmguerre** [comment]
You can pass a callback function to the `run` method:

```python
algorithm.run(1000, callback=foo)
```

and then create the `foo` function, that receives an instance of the algorithm. This function will be called after each `step` in the algorithm.
Inside this `foo` function you can do whatever you want, for instance, save all generations for a later analysis.

AFAIK this is the only way to get the solutions for each generation...
