### ISSUE TITLE
A proper release would be useful

### ISSUE THREAD

**Issue by mhucka** [Project-Platypus/Platypus#11]
Thanks for creating Platypus.

I've started successfully using Platypus for some simple optimizations. In order to communicate to other people which version of Platypus I'm using (particularly in code that I develop), it would be really useful to have a proper release to reference.  Failing that, at least a version number within the code itself would help.

**Comment by dhadka** [comment]
Do you need the release to be on PyPI?

**Comment by jetuk** [comment]
Not necessarily, though that would be useful in general. I have been mostly using conda for distribution and CI of my project hence the comment re the conda build recipe. I don't mind writing that recipe but I think a prerequisite is for there to be version number or at least tag in the repo.

**Comment by dhadka** [comment]
Ok, created tag 1.0.0.  This version is also now on PyPI under the name "Platypus-Opt" (unfortunately "Platypus" was already taken) and can be installed using `pip install platypus-opt`.

**Comment by jetuk** [comment]
Thanks! Do you have any interest in a conda recipe / build? If not I'll upload it to my project's channel. I'll leave a link here when it's done.

**Comment by jetuk** [comment]
A quick update on this. I've written the recipe with the intention of submitting it to conda-forge. See WIP below.

https://github.com/jetuk/staged-recipes/tree/platypus-opt/recipes/platypus-opt

This currently doesn't work with the source distribution on pypi due to missing tests and licence file. I've opened #54 to address that, but it will require a reupload of the modified distribution to pypi.

**Comment by dhadka** [comment]
Thanks!  Can't re-upload but I created version 1.0.1:
* https://github.com/Project-Platypus/Platypus/releases/tag/1.0.1
* https://pypi.python.org/pypi/Platypus-Opt/1.0.1

**Comment by jetuk** [comment]
@dhadka the last official release was nearly 2 years ago. Could there be a new release? I'm happy to help with the packaging/releases if that would help?

**Comment by dhadka** [comment]
@jetuk Published 1.0.4.  Thanks!
