### ISSUE TITLE
Same answer for all of the result population and Extera iteration

### ISSUE THREAD

**Issue by s-m-amin-ghasemi** [Project-Platypus/Platypus#111]
I am using NSGA2.

1- Some time the result member are same but when I look other generations they are not same.

2- Why some time it make more iteration than what I set in run(…) and those generation have less population ?

`
algorithm = NSGAII(structureoptimiser(),functions_POCD_PBE.population_size_num)
algorithm.run(functions_POCD_PBE.mainiterations)
`

![image](https://user-images.githubusercontent.com/42154749/66220762-74e5ff80-e6da-11e9-88b7-5df256fa62a7.png)

**Comment by fhalawa1** [comment]
have you figured this out? I have a problem also. Each time I run the algorithm it gives me a different value. 
In this example, does it mean that population size =1000 and generations =10 ? 
How to set the number of generations ? 
algorithm = NSGAII(problem,population_size=PopSize)
algorithm.run(10)

**Comment by s-m-amin-ghasemi** [comment]
@fhalawa1 
About my issue, unfortunately no.

1- I think yes, I am using functions for setting population and generation like what you said.
2- But for each run different value is basic of stochastic algorithm specially non-dominated one like NSGAII so it is not wrong to get different value for each run.
Just find some evidence that make you confirm that your pareto plot is logical.
