### ISSUE TITLE
Pickle bug during parallelization

### ISSUE THREAD

**Issue by simon19891101** [Project-Platypus/Platypus#114]
Hi there, has anyone got "TypeError: can't pickle _thread.lock objects" during parallelization? I'm using python 3.7.3 and platypus 1.0.3. Much appreciated for your help!

My parallelization is below:

    with ProcessPoolEvaluator(10) as evaluator:
        algorithm = NSGAII(problem, population_size=n_population, evaluator=evaluator)
        algorithm.run(n_population*n_generation)

**Comment by simon19891101** [comment]
Resolved. Have to tightly follow the way the functions are imported in https://github.com/Project-Platypus/Platypus/blob/master/examples/simple_parallel.py instead of using 

from platypus import *

**Comment by dhadka** [comment]
@simon19891101 Thanks for reporting this.  I'm going to create a separate issue to look into fixing the imports.  Ideally, `from platypus import *` should work.

**Comment by simon19891101** [comment]
Hi @dhadka, thanks. Had a go for "from platypus import *" and it worked this time. Probably because the python was upgraded from 3.6.8 to 3.7.3.
