### ISSUE TITLE
Creating multiple variables

### ISSUE THREAD

**Issue by Erison356** [Project-Platypus/Platypus#116]
Hello! 

In my program, I have about 400 variables that will be considered in my NSGA-II problem. Is there any way how to assign such huge amount of variables with vars[] without writing different variable names over and over again? And another thing, how does vars[] work in multivariate multiobjective optimization? Please enlighten me.

**Comment by clementb7596** [comment]
I have the same problem

**Comment by myzjy8** [comment]
fighting, I've been stuck for almost two months，sad

**Comment by domingo-valdes** [comment]
Im solving for 4500 variables. Just do something like this:

for i in range(1000):
    my_list.append(solution.variables[i])

then you can access the variables in my_list
