### ISSUE TITLE
Round numbers in the MOEA

### ISSUE THREAD

**Issue by Jmiguel17** [Project-Platypus/Platypus#117]
Hi @jetuk,

I was wondering how to round the float numbers in the optimisation? at the moment I am getting floats values with many decimals. I was thinking about adding `np.roud()` in the `def evaluate` method from the `platypus.py` file, where is setting the values of the variables, objectives and constraints. However, my question is if this would be right. could this have an impact on the optimisation?? 

Thanks

**Comment by dhadka** [comment]
I assume by the "evaluate method" you're referring to the one that defines your specific problem?  If so, yes, that's were I would recommend performing any rounding.
