### ISSUE TITLE
Indicators: Documentation Needed

### ISSUE THREAD

**Issue by chicodelarosa** [Project-Platypus/Platypus#12]
Can you provide documentation on how to implement the indicators?

**Comment by dhadka** [comment]
Hi, sorry for not responding earlier.   My Java library has a good amount of documentation on these indicators here: 

https://github.com/MOEAFramework/MOEAFramework/tree/master/src/org/moeaframework/core/indicator.

The Python implementations are directly translated from the Java version, so the documentation should match up.  You can also find details on these indicators in this paper: 

> Knowles, J. and D. Corne.  "On Metrics for Comparing Non-Dominated Sets."  Proceedings of the 2002 Congress on Evolutionary Computation, pp. 711-716, 2002.
