### ISSUE TITLE
Generate reproducible result

### ISSUE THREAD

**Issue by ivan-marroquin** [Project-Platypus/Platypus#13]
Hi,

Is there a way to fix a seed in order to get reproducible results? If so, could you show me how to do that.

Many thanks,

Ivan

**Comment by dhadka** [comment]
Currently, all random numbers are generated by the [random module](https://docs.python.org/2/library/random.html).  So calling `random.seed(N)` at the beginning of your code will set the seed.

This will only work for serial runs (i.e., no threading / parallelization).

**Comment by ivan-marroquin** [comment]
thank you so much
