### ISSUE TITLE
downloading Platypus with condas 

### ISSUE THREAD

**Issue by sabrinadraude** [Project-Platypus/Platypus#132]
I get the following issues when trying to install Playtypus using condas. When I use pip install on python it works perfectly fine. 
I used the following code:
conda config --add channels conda-forge
    conda install platypus-opt

Please help :) 
![87947326_2716076918439468_1803122657789476864_n(1)](https://user-images.githubusercontent.com/53531195/75312778-e756a800-5852-11ea-8d5a-1c943dced0d0.jpg)

**Comment by jetuk** [comment]
You have a misconfigured conda channel here. The "https://pypi.org" channel is incorrect and should be removed.
