### ISSUE TITLE
maximization with NSGA III

### ISSUE THREAD

**Issue by harsha3080** [Project-Platypus/Platypus#137]
Is there any possible way using NSGA III for 3 objectives problem with 2 objectives are minimized and the one should be maximized?

**Comment by dhadka** [comment]
Yes, this should be possible by setting the `directions`:

```
problem.directions[0] = Problem.MINIMIZE
problem.directions[1] = Problem.MINIMIZE
problem.directions[2] = Problem.MAXIMIZE
```

**Comment by harsha3080** [comment]
Hi...Thanks for the reply but it says as it is shown in the attached figure.
![Capture](https://user-images.githubusercontent.com/50446733/78797704-5843c080-79b8-11ea-801e-dadc0a4bab23.PNG)

**Comment by dhadka** [comment]
Oh, lol...thanks for pointing that out :) I don't remember why I didn't add support for maximizing...

Alternatively, you can negate the objective value instead.  Maximizing objective `f(x)` is the same as minimizing `-f(x)`.

**Comment by harsha3080** [comment]
Yeah....thanks dhadka. Let me try that....i am just comparing nsga 2 and nsga 3 for an engineering problem with 3 objectives. Nsga 2 is giving distributed results while nsga 3 is sticking to the small part. Anyway...thanks for the wonderful library.
