### ISSUE TITLE
How to run the "calculate" function as shown in the experimenter.py script

### ISSUE THREAD

**Issue by ivan-marroquin** [Project-Platypus/Platypus#14]
Hi David,

I have the following code:
random.seed(1969)

def inverse_layer(x):
   code lines

problem= Problem(8,8,8)
problem.types[:]= Real(0, 1)
problem.constraints[:]= ">=0"
problem.constraints[:]= "<=1"
problem.function= inverse_third_layer

algorithm= NSGAII(problem)
algorithm.run(700)

The script works as expected and I am able to print the output of objectives.

When I tried the commands:
hyp= Hypervolume(minimum= [0,0,0], maximum= [1, 1, 1])
hyp_result= calculate(algorithm.result.objectives, hyp)

I get this error message: TypeError: 'NSGAII' object does not support indexing

Is there a way to get around?

Many thanks,
Ivan

**Comment by dhadka** [comment]
The `calculate` function is designed to take the output from the `experiment(...)` function, which is a special structure (`dict`) containing multiple approximation sets.  Instead, you want to calculate the value for just one set.  So try

    hyp_result = hyp.calculate(algorithm.result)

See https://github.com/Project-Platypus/Platypus/blob/master/examples/indicator.py for some examples.

**Comment by ivan-marroquin** [comment]
Thanks for pointing to the example script. 

I noticed that a reference set must be defined, so then, I can have these commands:
hyp= Hypervolume(reference_set)
hyp_result= hyp.calculate(algorithm.result)

How do I create a reference set for my data? In the example script, it seems that a 3D box is created as reference set. But in my case, I have 8 decision variables bounded between (0,1). Can I still be able to use this  function as follows: 

reference_set = EpsilonBoxArchive([0.02, 0.02, 0.02,0.02, 0.02, 0.02,0.02,0.02])

or, how should I generate the reference set?

**Comment by dhadka** [comment]
It depends on your problem.  Is it one of the standard test problems (e.g., from the ZDT, DTLZ, WFG problem suites)?  If so, then there are known reference sets for these problems.

If your problem has no known reference set, then we typically generate a "best known" reference set, which is created by simply combining the best solutions from all runs you have available.  You can use `EpsilonBoxArchive` to aggregate the solutions across all runs.  

If you only need hypervolume, you can alternatively provide the minimum and maximum bounds.  For example, if you know your objectives will range between 0 and 10, you can say:

    hyp = Hypervolume(minimum=[0,0,0,0,0,0,0,0], maximum=[10,10,10,10,10,10,10,10])

**Comment by ivan-marroquin** [comment]
Thanks again!

Following you advice, I added the following lines:
hyp= Hypervolume(minimum= [0,0,0,0,0,0,0,0], maximum= [1,1,1,1,1,1,1,1])
hyp_result= hyp.calculate(algorithm.result)

Unfortunately, the command: display(hyp_result, ndigits= 10)

gives this error message:

AttributeError: 'float' object has no attribute 'keys'

**Comment by ivan-marroquin** [comment]
Thanks for all
