### ISSUE TITLE
@Erison356 `algorithm.run(100)` runs the program for 100 function evaluations (NFE).  For most algorithms, NFE = population_size * generations.  Thus, if you know the NFE and population size, you can get the number of generations.

### ISSUE THREAD

**Issue by strRang** [Project-Platypus/Platypus#144]
@Erison356 `algorithm.run(100)` runs the program for 100 function evaluations (NFE).  For most algorithms, NFE = population_size * generations.  Thus, if you know the NFE and population size, you can get the number of generations.

_Originally posted by @dhadka in https://github.com/Project-Platypus/Platypus/issues/79#issuecomment-534086702_

**Comment by MathewWalter** [comment]
Could someone please explain:

I'm using NSGA-II with a population_size = 100 and run(1000), how these nfe's are calculated?

input: print(nfe at each generation)

output: 100
196
293
390
484
579
673
766
864
959
1049

I was expecting 

output: 100
200
300
400
....
1000
