### ISSUE TITLE
Is it possible to run 'hyp.calculate' on individual instances of 'algorithm.result'?

### ISSUE THREAD

**Issue by ivan-marroquin** [Project-Platypus/Platypus#15]
Hi David,

I have the following code:

random.seed(1969)

def inverse_third_layer(x):
    b= inverse_desired_output    
    W= weights_third_layer
    bias= third_layer_bias
    
    return [np.sum(W[0,:])*x[0] - np.sum(b + bias), np.sum(W[1,:])*x[1] - np.sum(b + bias), np.sum(W[2,:])*x[2] - np.sum(b + bias), np.sum(W[3,:])*x[3] - np.sum(b + bias), 
            np.sum(W[4,:])*x[4] - np.sum(b + bias), np.sum(W[5,:])*x[5] - np.sum(b + bias), np.sum(W[6,:])*x[6] - np.sum(b + bias), np.sum(W[7,:])*x[7] - np.sum(b + bias)], [x[0], 
                  x[1], x[2], x[3], x[4], x[5], x[6], x[7]]

problem= Problem(8, 8, 8)

problem.types[:]= Real(0, 1)
problem.constraints[:]= ">=0"
problem.constraints[:]= "<=1"
problem.function= inverse_third_layer

algorithm= NSGAII(problem, population_size= 50, variator= UNDX()) 
algorithm.run(1000)

From it, I get a population of 50 feasible solutions. I would like to compare each objective vector by using the Hypervolume function. For that, I was hoping to iterate through each population to compute the Hypervolume as follows:
hyp= Hypervolume(minimum= [0,0,0,0,0,0,0,0], maximum= [2,2,2,2,2,2,2,2])
hyp_result= hyp.calculate(algorithm.result[0])

which gives this error message: TypeError: 'Solution' object is not iterable

Do you have any suggestions?

Many thanks,
Ivan

**Comment by dhadka** [comment]
I think you just want to use `hyp.calculate(solution.result)`.  `solution.result` is the set of Pareto solutions; `solution.result[0]` is just one of those solutions.

**Comment by ivan-marroquin** [comment]
I am looking to see which individual 'solution.result' , among all set of solutions, is the Pareto dominant. I believe that the Pareto dominant should give the smallest Hypervolume value. 

If my supposition is correct, then is there a way to run the 'hyp.calculate' function on individual instances?

**Comment by dhadka** [comment]
I see. Try making a list with the solution.

    hyp.calculate([algorithm.result[0]])

**Comment by ivan-marroquin** [comment]
Thanks for the suggestion. Unfortunately, I still get the same message
 TypeError: 'Solution' object is not iterable

**Comment by dhadka** [comment]
Ok, thanks for trying. I'll set this up on my machine and get back to you.

**Comment by ivan-marroquin** [comment]
Would you like a copy of the data I am using?

**Comment by dhadka** [comment]
Interesting, the following is working for me:

```python

from platypus import *

problem = DTLZ2(3)

algorithm = NSGAII(problem, population_size=50, variator=UNDX())
algorithm.run(10000)

hyp = Hypervolume(minimum=[0, 0, 0], maximum=[1, 1, 1])

for solution in nondominated(algorithm.result):
    print("Hypervolume of", solution.objectives, "=", hyp.calculate([solution]))
```

Please try that.  If you still run into this issue, then it would be good to get a copy of your data to reproduce.  Thanks!

**Comment by ivan-marroquin** [comment]
You are the men! it worked like a charm. Perhaps, you could add this tip to the documentation. Could you briefly describe the command 'nondominated'?

Thanks so much!

**Comment by ivan-marroquin** [comment]
One last question: when using the command hyp= Hypervolume(minimum= [0,0,0,0,0,0,0,0], maximum= [2,2,2,2,2,2,2,2])

Does the minimum represent the nadir point, while the maximum represents the utopia point?

**Comment by dhadka** [comment]
nondominated takes the result of an algorithm (a list of solutions) and returns the non-dominated (Pareto efficient) solutions.

Platypus assumes that all objectives are minimized.  So in this case, minimum is the utopia point and maximum is the nadir point.

**Comment by ivan-marroquin** [comment]
Thanks for all!
