### ISSUE TITLE
Pareto-front

### ISSUE THREAD

**Issue by doup123** [Project-Platypus/Platypus#155]
Is there a way to get and store all Pareto solutions?

**Comment by Orbitography** [comment]
Hi, 

You can use the following code 

`
from platypus import NSGAII, DTLZ2

# define the problem definition
problem = DTLZ2()

# instantiate the optimization algorithm
algorithm = NSGAII(problem)

# optimize the problem using 10,000 function evaluations
algorithm.run(10000)

# display the results
for solution in algorithm.result:
    print(solution.objectives)

# keep only solutions that are part of the Pareto Front
nondominated_solutions = nondominated(algorithm.result)
`

Please check the documentation for an intro to Platypus 
[https://platypus.readthedocs.io/en/latest/](https://platypus.readthedocs.io/en/latest/)
