### ISSUE TITLE
can we use "population_size" parameter setting with EpsNSGAII and EpsMOEA

### ISSUE THREAD

**Issue by ivan-marroquin** [Project-Platypus/Platypus#17]
Hi David,

is it possible to use "population_size" parameter setting with EpsNSGAII and EpsMOEA? if not, how can I find the population size output by one of these techniques?

Many thanks,
Ivan

**Comment by dhadka** [comment]
Yes, both EpsMOEA and EpsNSGAII have a population_size parameter.  There are some difference though.

1) Both EpsMOEA and EpsNSGAII use an epsilon-dominance archive (hence the "Eps" in the name).  This archive doesn't have a fixed size, but instead restricts the number of solutions using the epsilons parameter.  The simplest way to think about it is that we place a grid over the objective space, where the size of a cell in the grid is epsilon x epsilon (you can specify different sizes per dimension by providing an array to the `epsilons` parameter, e.g., `epsilons = [0.1, 0.25, ...]`).  Only one solution can exist in each cell.  The size of the epsilons bounds the number of solutions in the archive.  This is why the number of solutions in the result is different than the population size.

2) EpsNSGAII dynamically changes the population size.  So the `population_size` parameters is used to set the initial population, but it will increase or decreases as prescribed by the algorithm.

These algorithms are based off of the Java implementations in the MOEA Framework.  You can find information and references for each algorithm in https://github.com/MOEAFramework/MOEAFramework/releases/download/v2.12/MOEAFramework-2.12-BeginnersGuidePreview.pdf.

**Comment by ivan-marroquin** [comment]
Thanks a lot!
