### ISSUE TITLE
need help to set constrained conditions

### ISSUE THREAD

**Issue by ivan-marroquin** [Project-Platypus/Platypus#18]
Hi David,

The online documentation gives good examples on how to set up constraints using a numeric value. I have the following question for you, I read a 2D array from an input file and determine min/max values per column. Then, I want to use these values to set a group constraints as follows:

problem.constraints[0]= ">=logs_min[0]"
problem.constraints[0]= "<=log_max[0]"
problem.constraints[1]= ">=logs_min[1]"
problem.constraints[1]= "<=log_max[1]"
problem.constraints[2]= ">=logs_min[2]"
problem.constraints[2]= "<=log_max[2]"
problem.constraints[0]= ">=logs_min[3]"
problem.constraints[0]= "<=log_max[3]"

I get the following error message: could not convert string to float: 'logs_min[0]'

I haven't been able to find a way to feed the min/max values to the above mentioned commands.

Any suggestions?

Thanks

Ivan

**Comment by dhadka** [comment]
I suspect the constraint code expects the constraint to contain a numeric value rather than a variable name.  It should work if you create a string with the numeric value.  For example:

```python

problem.constraints[0] = ">=" + str(logs_min[0])
```

**Comment by ivan-marroquin** [comment]
now, it's much clearer!
