### ISSUE TITLE
Switch from Nose to Pytest (or other test framework)

### ISSUE THREAD

**Issue by EwoutH** [Project-Platypus/Platypus#184]
[Nose](https://github.com/nose-devs/nose) doesn't support Python 3.10 (as can be seen in #183), so testing should be switched over to another framework, [pytest](https://github.com/pytest-dev/pytest) for example.

**Comment by dhadka** [comment]
I have https://github.com/Project-Platypus/Platypus/pull/185 ready to switch to pytest once your PR merges.
