### ISSUE TITLE
Enable Read the Docs generation on Pull Requests

### ISSUE THREAD

**Issue by EwoutH** [Project-Platypus/Platypus#198]
Read the Docs allows you to generate docs for PRs, so that you immediately can check if your code and docs changes processed right. This makes validating and reviewing PRs that include docs changes easier.

See this link for more details: [Preview Documentation from Pull Requests](https://docs.readthedocs.io/en/stable/pull-requests.html)

**Comment by dhadka** [comment]
This is enabled.

**Comment by EwoutH** [comment]
Awesome, thanks!
