### ISSUE TITLE
Running in parallel - experimenter has no map/submit

### ISSUE THREAD

**Issue by fab6** [Project-Platypus/Platypus#2]
Hello,
when trying to run the parallel examples from the doc, I get this error for the concurrent.futures variant:

Traceback (most recent call last):
  File "exp_multi.py", line 48, in <module>
    results = experiment(algorithms, problems, nfe=10000, submit=pool.submit)
TypeError: experiment() got an unexpected keyword argument 'submit'

For multiprocessor it has as unexpected keyword argument 'map'

Would be great, if you have an advice to fix this.

**Comment by fab6** [comment]
Hello,
did you have a chance to look at this? It would be great, if you have a hint.
Thanks!
Best Regards

**Comment by dhadka** [comment]
Hi @fab6, The documentation is now updated with a working example.  You can also find these examples in the new `examples/` folder.

**Comment by fab6** [comment]
Hello, great! Thank you! Is there a chance to get the current job id? I need to create external calculates in subdirectories.
