### ISSUE TITLE
Make it clear that `platypus.Integer` uses gray code

### ISSUE THREAD

**Issue by this-josh** [Project-Platypus/Platypus#201]
This is an issue related to #200. :

From reading through the test files, it seems that `also.result[0].variables[0]` is not a binary number, it is [Gray code](https://en.wikipedia.org/wiki/Gray_code). Might I suggest this is made more clear as the word 'gray' doesn't appear at all in [the docs](https://platypus.readthedocs.io/en/latest/search.html?q=gray&check_keywords=yes&area=default) and most people who see `[True, False, True]` will view it as binary. 

_Originally posted by @this-josh in https://github.com/Project-Platypus/Platypus/issues/200#issuecomment-1301853413_

**Comment by dhadka** [comment]
This is called out in the Python docs - https://github.com/Project-Platypus/Platypus/blob/3fec9d1737f11b7fc763bbbfbb9b05d0e4d80dc4/platypus/types.py#L111-L122

**Comment by this-josh** [comment]
This is not the docs, this is the docstring. You don't typically expect users to read through the code to find doc strings and if that is what you expect them to do I think it should be made explicit. For example [integer](https://platypus.readthedocs.io/en/latest/search.html?q=Integer&check_keywords=yes&area=default#) is also not present in the docs, nor is [decode](https://platypus.readthedocs.io/en/latest/search.html?q=decode&check_keywords=yes&area=default#). But as you point out the doc strings have been written, so I refer to my initial issue that this should all be made clearer in the [docs](https://platypus.readthedocs.io/en/latest/index.html)
