### ISSUE TITLE
GEX_phenotype function does nothing

### ISSUE THREAD

**Issue by beginner984** [Project-Platypus/Platypus#211]
Hi

I have integrated my 5' GEX with TCR but I guess `GEX_phenotype` function does not work as in my metadata all I see is `Unclassified`

`vgm[[2]] <- GEX_phenotype(vgm[[2]], default = T)`

Any idea please?

Thank you

**Comment by dhadka** [comment]
Hi, this doesn't appear to be part of this library.  I think you're using https://github.com/alexyermanos/Platypus, please reach out to the authors there!  😄
