### ISSUE TITLE
ImportError: cannot import name 'default_variator' from 'platypus'

### ISSUE THREAD

**Issue by EwoutH** [Project-Platypus/Platypus#246]
Our CI detected a new import error, on using platypus-opt 1.3.0.

```
ImportError: cannot import name 'default_variator' from 'platypus'
```

- Last week, the [build passed](https://github.com/quaquel/EMAworkbench/actions/runs/10554606242/job/29236737082), using platypus-opt 1.2.0
- This week, the [build failed](https://github.com/quaquel/EMAworkbench/actions/runs/10661818843/job/29547946575), using platypus-opt 1.3.0

Location the import error originates from: [outputspace_exploration.py#L30](https://github.com/quaquel/EMAworkbench/blob/561fda7a8bbb48126430f73a6f97eb1c21de2cef/ema_workbench/em_framework/outputspace_exploration.py#L30)

**Comment by dhadka** [comment]
I sent a PR to EMAWorkbench with two possible fixes.  One in the PR and one in the PR's description, depending if you want to support both versions of just 1.3.0 moving forward.

https://github.com/quaquel/EMAworkbench/pull/369

**Comment by dhadka** [comment]
Version `1.3.1` is published that adds these methods back.  However, they now warn about being deprecated, so you may still see CI errors if `pytest` is configured to fail on warnings.

If it's still causing issues for your CI, you might need to ignore these with something like:

```python
import warnings
warnings.filterwarnings('ignore', message=".*PlatypusConfig.*", category=DeprecationWarning)
```

or 

```bash
-Wignore::DeprecationWarning::
```

**Comment by EwoutH** [comment]
Thanks for both the bugfix release and the solutions provided!
