### ISSUE TITLE
Error while running ProcessPoolEvaluator in iPython

### ISSUE THREAD

**Issue by rebinth** [Project-Platypus/Platypus#27]
While running ProcessPoolEvaluator in Windows iPython environment, I have the following error.

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by manuparra** [comment]
Hello! Paste your code @rebinth

**Comment by rebinth** [comment]
I am using the simple_parallel.py platypus example and get the above error.

**Comment by dhadka** [comment]
Hi, there may be some incompatibility between the ProcessPoolEvaluator used in that example and iPython.  I'll need to investigate the cause.  In the meantime, I would suggest trying the MultiprocessingEvaluator to see if it works in iPython.  Thanks!

**Comment by dhadka** [comment]
Also, note that both ProcessPoolEvaluator and MultiprocessingEvaluator can not be run interactively according to the [documentation](https://docs.python.org/3/library/concurrent.futures.html):

> The `__main__` module must be importable by worker subprocesses. This means that ProcessPoolExecutor will not work in the interactive interpreter.

If not already, please make sure you're running the example from the command line and not in some interactive mode.

**Comment by rebinth** [comment]
Do we have any option to have it run interactively in Spyder iPython.

**Comment by rebinth** [comment]
When I run the function for more than 100 times, I get the following error..

Traceback (most recent call last):
  File "Optimization_Scipy_03.py", line 179, in <module>
    algorithm.run(104)
  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\platypus\core.py", line 302, in run
    self.step()
  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\platypus\algorithms.py", line 175, in step
    self.iterate()
  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\platypus\algorithms.py", line 196, in iterate
    offspring.extend(self.variator.evolve(parents))
  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\platypus\operators.py", line 190, in evolve
    return list(map(self.mutation.evolve, self.variation.evolve(parents)))
  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\platypus\core.py", line 173, in evolve
    return self.mutate(parents)
  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\platypus\operators.py", line 80, in mutate
    problem.types[i].max_value)
  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\platypus\operators.py", line 91, in pm_mutation
    bl = (x - lb) / dx
ZeroDivisionError: float division by zero

**Comment by rebinth** [comment]
How to the specify the number of iterations / population size? Do we have a manual that summarizes the same.

**Comment by matheusft** [comment]
> When I run the function for more than 100 times, I get the following error..
> 
> Traceback (most recent call last):
> File "Optimization_Scipy_03.py", line 179, in 
> algorithm.run(104)
> File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\platypus\core.py", line 302, in run
> self.step()
> File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\platypus\algorithms.py", line 175, in step
> self.iterate()
> File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\platypus\algorithms.py", line 196, in iterate
> offspring.extend(self.variator.evolve(parents))
> File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\platypus\operators.py", line 190, in evolve
> return list(map(self.mutation.evolve, self.variation.evolve(parents)))
> File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\platypus\core.py", line 173, in evolve
> return self.mutate(parents)
> File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\platypus\operators.py", line 80, in mutate
> problem.types[i].max_value)
> File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\platypus\operators.py", line 91, in pm_mutation
> bl = (x - lb) / dx
> ZeroDivisionError: float division by zero

I'm getting the same error every time I set the population greater than 100

**Comment by dhadka** [comment]
@matheusft Please check the lower and upper bounds of your decision variables and make sure they are not the same.  This error suggests `dx` is 0, and since `dx = ub - lb` this means the lower and upper bounds are the same.

**Comment by matheusft** [comment]
Spot on!
I had one decision variable with the same lower and upper bounds.
Thanks
