### ISSUE TITLE
problem about the PMX(Variator)

### ISSUE THREAD

**Issue by smjmingjie** [Project-Platypus/Platypus#3]
I  define a  problem with the variable type of Permutation, for example [0,1,0]. When I try to run the NSGAII , it gives me the following message .

 File "C:\Python27\ArcGIS10.3\Lib\site-packages\platypus\operators.py", line 638, in evolve
    o1[i] = p2[i]
IndexError: list assignment index out of range

I have checked the PMX(Variator), but I cannot figure out the problem. Do you have any idea about the problem?

**Comment by dhadka** [comment]
Hi,

Sorry for not responding sooner.  I wasn't setup to receive e-mails when new issues were opened.  The problem is fixed.

Thanks!
