### ISSUE TITLE
Constraints not respected always

### ISSUE THREAD

**Issue by sellisd** [Project-Platypus/Platypus#32]
Running an algorithm with a relatively small number of function evaluations gives results that do no respect the constraints of the problem. It seems to me that more these should not be included in the results.

```Python
# load libararies
from platypus import NSGAII, Problem, Real
import matplotlib.pyplot as plt

# define optimization function
def belegundu(vars):
    x = vars[0]
    y = vars[1]
    return [-2*x + y, 2*x + y], [-x + y - 1, x + y - 7]

# setup problem
problem = Problem(2, 2, 2)
problem.types[:] = [Real(0, 5), Real(0, 3)]
problem.constraints[:] = "<=0"
problem.function = belegundu
algorithm = NSGAII(problem)

# run algorithm and plot contstraints
algorithm.run(100)
x1= [s.constraints[0] for s in algorithm.result]
algorithm.run(10000)
x2= [s.constraints[0] for s in algorithm.result]

plt.hist(x1)
plt.hist(x2)
plt.xlabel("Constraint")
plt.ylabel("counts")
plt.legend(["100","1000"], title = "Function evaluations")
plt.show()
```
![constraints](https://user-images.githubusercontent.com/7484504/34877259-9db62e60-f7a5-11e7-8db0-c48c2585b92f.png)

**Comment by dhadka** [comment]
This is by design.  When using NSGAII without an archive, algorithm.result is the final population.  As such, the final population can contain infeasible and dominated solutions.

You would need to filter out the infeasible solutions:

```
    feasible_solutions = [s for s in algorithm.result if s.feasible]
```

You may also want to get only non-dominated solutions:

```
    nondominated_solutions = nondominated(algorithm.result)
```
