### ISSUE TITLE
Set a seed for Problem

### ISSUE THREAD

**Issue by manuparra** [Project-Platypus/Platypus#35]
Hello, Can I set a seed for a simple `Problem`?

Where will be set the seed ? In `Problem` 
```
from platypus import Problem, Real, NSGAII, Integer,Subset,Permutation

class Test(Problem):
    def __init__(self):
        super(Test, self).__init__(8,1,6)
        ...
```

or in `Algorithm`: 

`algorithm = NSGAII(Test,....)`

Thanks.

**Comment by dhadka** [comment]
Platypus uses Python's random module, so you would set the seed with:

```python

random.seed(12345)
```

You can call this anytime.  However, for consistency, it's good to call it before creating the algorithm:

```python

random.seed(12345)
algorithm = NSGAII(Test, ...)
```

If you're running an algorithm multiple times, you can include it in your loop:

```python

for i in range(10):
    random.seed(i)
    algorithm = NSGAII(Test, ...)
```

**Comment by manuparra** [comment]
Thanks !
