### ISSUE TITLE
Multiprocessing single algorithm on single problem

### ISSUE THREAD

**Issue by ghost** [Project-Platypus/Platypus#36]
Hi,
I try to use the experimenter to run a three-dimensional problem with NSGA III and 1000 evaluation runs in parallel. The reason is that without parallelization it last 30h to compute it.

I do not want to compare different algorithms or problems. Can I force the experimenter to run thsi single problem with one algorithm in parallel?

Or do you have othe rrecommendations how to spead up the computation of this problem.

Thanks for your support!
Fabian

**Comment by dhadka** [comment]
Try parallelizing this way: https://github.com/Project-Platypus/Platypus/blob/master/examples/simple_parallel.py

**Comment by badchild0912** [comment]
Hi, @dhadka  
Thank you for your demo. 
I also try to run the single algorithm in parallel to accelerate it, but I don't clearly understand the way you define the DTLZ2_Slow.
```
class DTLZ2_Slow(DTLZ2):
    
    def evaluate(self, solution):
        sum(range(1000000))
        super(DTLZ2_Slow, self).evaluate(solution)
```
Could you explain a little bit what sum and super sentences exactly do here? 
Besides, we set the algorithm run 10000 times and set 4 the evaluator, so the algorithm run 40000 times? Or 4 evaluators finish the 10000 times iterators together?

Thank you in advance.
Hanwei
