### ISSUE TITLE
Question: is there a way to order a set of nondominated solutions?

### ISSUE THREAD

**Issue by ivan-marroquin** [Project-Platypus/Platypus#39]
Hi David,

I found this paper: https://pdfs.semanticscholar.org/5757/e76802152ca7d4df6395e553017bf42b59ce.pdf

the authors propose an interesting way to select the nadir point from the generated solutions in the Pareto front. Part of the workflow requires to order the nondominated solutions from maximum to minimum. Then the sorted solutions are ranked according their position.

Does Platypus has an internal function to sort the nondominated solutions? 

Many thanks,

Ivan

**Comment by dhadka** [comment]
From a quick skim, it sounds like they order the solutions by each objective when assigning the rankings.  You can do something like this:

```python

solutions = algorithm.result
solutions.sort(key=lambda s : s.objectives[0]) # Sort by first objective

for i, s in enumerate(solutions):
    s.ranking = i
```

**Comment by ivan-marroquin** [comment]
Thanks a lot!
