### ISSUE TITLE
Obtaining Values of parameters for optimal function

### ISSUE THREAD

**Issue by hardikmeisheri** [Project-Platypus/Platypus#4]
Can anyone please tell how can I find the values of variables after algorithm.run()

**Comment by dhadka** [comment]
Use `solution.variables`.  For example, you can display the decision variables as follows:

```python

for solution in algorithm.result:
    print(solution.variables)
```

You can also use `solution.objectives` and `solution.constraints` to retrieve the objectives and constraints, respectively.

**Comment by hardikmeisheri** [comment]
By using the Above 

for solution in algorithm.result:
    print(solution.variables)

I get a bunch of result on screen but not the final value of paramter for which the objective function is optimized.

**Comment by Evidlo** [comment]
Run `algorithm.result[0].__dict__` and you can see how a result is structured.
