### ISSUE TITLE
Parallelizing with 24 physical cores

### ISSUE THREAD

**Issue by manuparra** [Project-Platypus/Platypus#40]
Hi, I want to use 24 cores or my computer (node);
I have this code to parallelize in python 2.7:

```
with platypus.MultiprocessingEvaluator(24) as evaluator:

                        algorithm = platypus.NSGAII(Material(),evaluator=evaluator)
                        algorithm.run(250000)
```

But when I see CPU consumption with `htop` I see that cores are infraused (at least 24):

![image](https://user-images.githubusercontent.com/7033451/35556033-63040cba-05a1-11e8-8938-d4dde51784ac.png)

How can I modify for evaluations of indicators to be done in parallel?
Do I need something to the `Problem` in the `evaluation` function on `Material()` @dhadka ?

**Comment by dhadka** [comment]
I've seen it before where if the evaluation time is so short, the parallel evaluations simply can't consume all CPU resources.  Essentially, the previous evaluation(s) were finishing before the multiprocessing code could dispatch the next parallel task, so it never filled up all parallel threads.

A quick way to test this is to add some extra calculations to slow down your evaluations.  I did this in `example/simple_parallel.py` by just adding a summation:

```python

class DTLZ2_Slow(DTLZ2):
    def evaluate(self, solution):
        sum(range(1000000))
        super(DTLZ2_Slow, self).evaluate(solution)
```

I would recommend trying this and report back if you still only see a few CPUs being consumed.

**Comment by manuparra** [comment]
Thanks, solved!. Using extra calculations I can see CPU usage to 100%.
