### ISSUE TITLE
custom made types

### ISSUE THREAD

**Issue by aziz86** [Project-Platypus/Platypus#41]
Hi,

I was wondering whether I should recompile the whole project when I create a new encoding scheme rather than use the ones included (i.e Binary, Permutation, etc.) ?

Could you please shed some light on this concern because I am working on a specific problem for which I need to use a custom encoding scheme.

Thanks.
Aziz

**Comment by dhadka** [comment]
Hi,

Thanks for your inquiry.  I'm not sure what you mean about recompiling the whole project.  If you installed Platypus using `python setup.py install`, you will need to re-install it using the same command after making code changes.  You could also use `python setup.py develop` so you don't need to reinstall after every change (see https://stackoverflow.com/a/19048754)

To add a custom encoding scheme, you need to make three changes:
1. Create the new custom encoding scheme by subclassing Type (see types.py for examples)
2. Create the operators for your new type (see operators.py for examples)
3. Update default_variator and default_mutation in config.py.  Here you specify the default operators to use for each type.

**Comment by aziz86** [comment]
Hi,
Ooops it was not recompiling I meant literally as in Python it is interpretation but It was re-installing yeah. Thanks a lot for your reply and clarifications it answers my inquiry.

All the best
