### ISSUE TITLE
custom made type conflicting with FixedLengthArray class

### ISSUE THREAD

**Issue by aziz86** [Project-Platypus/Platypus#46]
Hi there,
I recently closed an [issue](https://github.com/Project-Platypus/Platypus/issues/41) regarding a custom made type. 
I successfully added a custom type which is in the form of a matrix of size AxB where A=2 and B is of size N. The first column contains tuples while the second columns contains a list.

I am getting this error :

> Traceback (most recent call last):
>   File "/home/myProblem.py", line 34, in <module>
>     print myprob.types
>   File "/home/Platypus/platypus/core.py", line 80, in __str__
>     return "[" + ", ".join(list(map(str, self._data))) + "]"
> TypeError: __str__ returned non-string (type tuple)
> 
It seems that I need to modify FixedLengthArray class also, is that right ?
Could you please shed some lights ? Any suggestion ?
Thanks

**Comment by dhadka** [comment]
The error seems to indicate it is calling the __str__ method on your custom type but is getting a tuple back when it expects a string.  I would recommend ensuring that your __str__ method returns a string.  If you include the code for your custom type, I can also take a look.  Thanks!

**Comment by aziz86** [comment]
Hi @dhadka ,
Thanks for answering. I had a look to where the error comes from and its coming from **str** method of FixedLengthArray class. I added the **str** method to my custom type and now it works as you suggested.
Regards!

**Comment by aziz86** [comment]
Hi @dhadka,
It seems that I need to modify a bunch of methods, I want to use NSGAII by the way. Here is a [link](https://github.com/aziz86/test/blob/master/ga_type.py) to my custom made type, thanks.
Regards

**Comment by dhadka** [comment]
Thanks for sharing your code.  You'll want something like:

```python

class myMatrix(Type):
    def __init__(self, serversIdentifiers, virtualLinks):
        super(myMatrix, self).__init__()
        self.virtualLinks = virtualLinks
        self.serversIdentifiers = serversIdentifiers

    def rand(self):
        matrix = [[0 for x in range(2)] for y in range(len(self.virtualLinks))]

        for k in range(len(self.virtualLinks)):
            matrix[k][0] = (self.virtualLinks[k], self.virtualLinks[k]+1)
            matrix[k][1] = random.sample(self.serversIdentifiers, random.randint(2, len(self.serversIdentifiers)))

        return matrix

    def __str__(self):
        return "myMatrix(%s, %s)" % (self.serversIdentifiers, self.virtualLinks)
```

The key changes are:

1. Separate the Type definition from the values of that type.  The class myMatrix should only store information about the type itself.  For example, the Integer type only stores the lower and upper bounds.  So I removed `self.matrix` from the init method.

2. The rand() method returns a randomly-generated value for this type.  So here it's returning the matrix object you're creating.

You can test this with:

```python
from platypus import *

def eval(vars):
    matrix = vars[0]
    print(matrix)
    return 0 #Replace with actual objectives

problem = Problem(1, 1, 0)
problem.types[:] = [myMatrix(...)]
problem.function = eval

algorithm = NSGAII(problem)
algorithm.run(100)
```

If you run this, it'll print out the matrices for the randomly-generated initial population.

**Comment by aziz86** [comment]
@dhadka God bless you and thank you so much !
