### ISSUE TITLE
Documentation/Feature Request: Convergence Rates/Method

### ISSUE THREAD

**Issue by SterlingButters** [Project-Platypus/Platypus#48]
I have a project that handles ~70k parameters and I am trying to decide if Platypus is capable of handling such a vast parameter space. I feel it would be beneficial to provide in the documentation how convergence rates change with number of parameters. 

Also, kind of inline with convergence, would it be possible to implement Playpus via 
`while not_converged == True:
    run()` 

Instead of `run(iterations)` because in this alternate scenario you can just assume that after enough time has elapsed it will either not converge, or it will not converge in desired time.

**Comment by dhadka** [comment]
Thanks for the recommendations.  I don't have any convergence numbers on hand.

Yes, normally you call the algorithm.run(...) method with the number of function evaluations, but you can also pass in a TerminationCondition instance (see https://github.com/Project-Platypus/Platypus/blob/master/platypus/core.py#L195).  If the TerminationCondition class doesn't give you enough flexibility, you can also use the algorithm.step() method which performs one iteration of the algorithm: `while not_converged: algorithm.step()`.

**Comment by SterlingButters** [comment]
Great! I’ll try that out and close this issue
