### ISSUE TITLE
An issue in the selection of the default Variator

### ISSUE THREAD

**Issue by Hebbalali** [Project-Platypus/Platypus#5]
Hello, 
I noticed that there is a small issue in the code. In the functions default_variator and default_mutator, in config.py. In fact, normally they must return the correspondig operator for the corresponding type of variables, and if there are mixed variables (Integer and Real for example) it must raise an error. However when i lunch the program with the NSGA II with mixed Variables he doesn't raise any error. 
So i noticed that " all([isinstance(t, base_type)] " alwyas return true even if t isn't an instance of base_type, and that is because of the brackets "[ ]' in fact if we write instead "all(isinstance(t, base_type)" the error is raised. 
This small issue caused me some big problems in fact, when i launch the NSGA II with the first variable as integer he systematicly use the integer variator even if the other variables are Real. So with removing the brackets the error is raised to tell us that a mixed operator must be used. 
And i want to thank you for the grat effort for developping such a project ! 
-----
Ali

**Comment by dhadka** [comment]
Hi, thanks for bringing this to my attention.  It will be fixed shortly.

**Comment by dhadka** [comment]
This was fixed a while ago in commit 438f866b12977dba0176db7fb28137920e19fd6e.  Closing.
