### ISSUE TITLE
How to understand the way of Generating weight vectors

### ISSUE THREAD

**Issue by eigeneko** [Project-Platypus/Platypus#55]
Hi ！
I'm new to this filed and try to read the code implementation.
The weight_generator of MOEA/D is random_weights. But I don't understand why this random generating method is used in Platypus.
The original paper of MOEA/D suggests a uniformly generating way. 
It seems the generate_recursive in normal_boundary_weights is more close to this approach. 
I know how it works but I'm confused about why it is used. You know in that paper, a H parameter is introduced to generated the weight vectors.Could you please give me some explanations. 
 Thanks!!

**Comment by dhadka** [comment]
Hi and welcome!

Yes, you're correct that they didn't use `random_weights` in the original MOEA/D.

In **Li, H. and Zhang, Q. "Multiobjective Optimization problems with Complicated Pareto Sets, MOEA/D and NSGA-II." IEEE Transactions on Evolutionary Computation, 13(2):284-302, 2009**, their approach is equivalent to using `normal_boundary_weights` with `divisions_outer = H` and `divisions_inner = 0`.

In **Zhang, Q., et al.  "The Performance of a New Version of MOEA/D on CEC09 Unconstrained MOP Test Instances."  IEEE Congress on Evolutionary Computation, 2009**, they introduced MOEA/D-DRA which supports dynamic resource allocation (the `update_utility` argument is used for this).  In this paper, they use the `random_weights` method.

So why would we use `random_weights`?  Well, the number of weights produced by `normal_boundary_weights` grows very quickly as the number of objectives increases. 

    >>> len(platypus.normal_boundary_weights(2, divisions_outer=100))
    101
    >>> len(platypus.normal_boundary_weights(3, divisions_outer=100))
    5151
    >>> len(platypus.normal_boundary_weights(4, divisions_outer=100))
    176851

Which means we need to adjust the value of `H` for every objective count.  Using `random_weights` is much easier...just tell it how many weights to generate.

Please note that while writing this response, I found a bug in how `weight_generator` was being handled and committed a fix. With this fix, you would use the different weight generators as follows:

    MOEAD(problem, population_size=100, weight_generator=random_weights)

or

    MOEAD(problem, divisions_outer=24, weight_generator=normal_boundary_weights)

**Comment by dhadka** [comment]
No problem!  I prefer having the issues created here since others may have the same or similar questions.  Closing this issue.
