### ISSUE TITLE
Run platypus in parallel on single seed

### ISSUE THREAD

**Issue by m-balesdent** [Project-Platypus/Platypus#6]
Hello,

I'd like to run a platypus process with evaluating my objective function (and constraints) in parallel. Unfortunately, I didn't succeed. I've try to use the "ProcessPoolEvaluator", but it allows me to only parallelize different runs of the same optimization algorithm (using seeds) but not to parallelize the function evaluations on the same platypus run.

Is there any way to do so in platypus?

Thanks.

**Comment by dhadka** [comment]
Please check out this example showing how to parallelize the function evaluations: https://github.com/Project-Platypus/Platypus/blob/master/examples/simple_parallel.py

**Comment by bernardo-suez** [comment]
@dhadka am I correct in my understanding that only two or three solutions are evaluated in parallel at a time ([here](https://github.com/Project-Platypus/Platypus/blob/62b5c23d2674839000388d463225224863d7b508/platypus/core.py#L408))? By two or three I mean however many children are generated at one iteration of an algorithm's operators call. If I'm correct, are there any plans to parallelize this either synchronously or (even better) asynchronously?
