### ISSUE TITLE
Can I use Platypus to solve Discrete MOFLPs? Also, does this NSGA-II work with constraints as well?

### ISSUE THREAD

**Issue by MelinaRentzi** [Project-Platypus/Platypus#65]
Hello,
I've been searching for a framework to solve a discrete multi-objective facility location problem, and I found your framework. As I understand, you have implemented some of the most popular testing problems for continuous optimization. Would I be able to use this framework to solve a discrete multiobjective facility location problem? I was thinking about using your NSGA-II algorithm and create my own custom MO function. Does your NSGA-II algorithm support constraints? If no, would I be able to create my own in the framework? Thanks a lot.

**Comment by mariocastrogama** [comment]
As I recall Platypus is built homologous to MOEA Framework.
The list of algorithms are similar to the ones presented in the following link
[http://moeaframework.org/javadoc/overview-summary.html#listOfAlgorithms](url)

1) Not sure what Facility Location Problem means, but Platypus supports Discrete variables (use Binary)
2) Does NSGA2 support constraints --> Yes
