### ISSUE TITLE
How to use nondominated_sort on a list of solutions

### ISSUE THREAD

**Issue by smnsierra** [Project-Platypus/Platypus#66]
Hello,
i have a list of solutions and the related objective functions (6) and constraints (1) that have been evaluated outside the platypus framework; they are stored as list of lists. 
```
solutions = [[var_1, var_2, ... , var_n],
             [var_1, var_2, ... , var_n],
             ...]

obj_funcs = [[of_1, of_2, ... , of_6],
             [of_1, of_2, ... , of_6],
             ...]

constr = [constr_1, constr_2, ... ]
```
Is it possible to perform the `nondominated_sort` on this set of objective functions evaluations? if so How could I do it?
I have noticed that the `nondominated_sort` function takes as input a set of solutions casted as a `Solution` class, defined in `platypus.core`.

Thank you very much for your help!

**Comment by dhadka** [comment]
Hi, please take a look at this example: https://github.com/Project-Platypus/Platypus/blob/master/examples/simple_indicators.py

You can see how it creates a Solution from objectives: 

    solution = Solution(problem)
    solution.objectives[:] = [x, math.sqrt(1.0 - x**2)]

You can set the constraints similarly.  Put these solutions in a list and call nondominated_sort.

Hope this helps!

**Comment by smnsierra** [comment]
Thank you very much for your prompt reply! This helps indeed. 
Shoud I provide a `solution.problem` as well?

**Comment by dhadka** [comment]
If you're just using the nondominated sorting function, you shouldn't need to.  Otherwise, it'll give you an error if you need it set.

**Comment by smnsierra** [comment]
i am doing this:
```
problem = Problem(1,nobjs,ncons) # Send 1 permutation, return 6 OF, and 1 constraint
problem.types[0] = Permutation(range(nvars)) # Permutation of elements [0, 1, ..., nvar-1]
problem.constraints[:] = "<=0"

lst = [Solution(problem) for i in range(n_solutions)]  #  List of the solutions casted from the Solution class

# Setting objectives and constraints
for i, item in enumerate(lst):
    item.objectives[:] = fitness[i][:-1]
    item.constraint_violation = fitness[i][-1]
    item.problem = problem

sorted = nondominated_sort(fitness)
```
and I get
```
Traceback (most recent call last):

  File "<ipython-input-67-34bd2b3a7cbb>", line 1, in <module>
    sorted = nondominated_sort(fitness)

  File "C:\Users\smnsi\Anaconda3\lib\site-packages\platypus\core.py", line 899, in nondominated_sort
    archive += solutions

  File "C:\Users\smnsi\Anaconda3\lib\site-packages\platypus\core.py", line 667, in __iadd__
    self.add(o)

  File "C:\Users\smnsi\Anaconda3\lib\site-packages\platypus\core.py", line 634, in add
    flags = [self._dominance.compare(solution, s) for s in self._contents]

  File "C:\Users\smnsi\Anaconda3\lib\site-packages\platypus\core.py", line 634, in <listcomp>
    flags = [self._dominance.compare(solution, s) for s in self._contents]

  File "C:\Users\smnsi\Anaconda3\lib\site-packages\platypus\core.py", line 432, in compare
    problem = solution1.problem
```

**Comment by dhadka** [comment]
Try `nondominated_sort(lst)`.

**Comment by smnsierra** [comment]
Ok sorry, I gave as input the wrong list. Now I corrected and don't get any error, but my `sorted` variable is a `NoneType` object.

**Comment by dhadka** [comment]
If you just want to get the non-dominated solutions, use `sorted = nondominated(lst)`.

`nondominated_sort` performs non-dominated sorting as described in NSGA-II, which computes the rank and crowding distance.  This function doesn't return anything.  Instead, it assigns the `solution.rank` and `solution.crowding_distance` attributes.
