### ISSUE TITLE
Unable to run basic example on Mac OS x

### ISSUE THREAD

**Issue by apfz** [Project-Platypus/Platypus#67]
I have installed platypus according to the instructions. However I am not able to run example files:

```
Traceback (most recent call last):
  File "/Users/f/app/Resources/solver/platypus.py", line 1, in <module>
    from platypus import NSGAII, Problem, Real
  File "/Users/f/app/Resources/solver/Resources/solver/platypus.py", line 1, in <module>
    from platypus import NSGAII, Problem, Real
ImportError: cannot import name 'NSGAII'
```

Any idea why the installation may not be complete?

**Comment by dhadka** [comment]
Hi, it's likely there is a different Python module installed with the same name.  If you are not using the other module, I would recommend uninstalling it first then installing Platypus again using the instructions in the readme file.  Thanks!
