### ISSUE TITLE
Use NSGAII com WFG.

### ISSUE THREAD

**Issue by joelalves21** [Project-Platypus/Platypus#69]
I would like to know how I use the NSGAII or NSGAIII algorithm for a WFG class ploblem?

I have tried the way below and have given error.

# define the problem definition
problem = WFG1(2)

# instantiate the optimization algorithm
algorithm = NSGAIII(problem, divisions_outer=12,variator = SBX(probability = 1.0, distribution_index = 30.0))

# optimize the problem using 100,000 function evaluations
algorithm.run(1000)

**Comment by dhadka** [comment]
Thanks for reporting this.  There were a few Python 3 compatibility issues.  They are now fixed in master.
