### ISSUE TITLE
Multiple/concurrent runs at once

### ISSUE THREAD

**Issue by nelinnemann** [Project-Platypus/Platypus#73]
Hi

First off thanks for a simple to use optimization library.

Is it possible to add multiple/concurrent runs at the same time?
I do a lot of CAD-CFD optimization and the runs tend to be quite long.
Not computational intensive as everything is run on a HPC queueing system (SGE).

I would like to instantiate X number of concurrent runs to allow for some speedup of the solution.
You could also say that I want to call the optimization problem/function multiple times with different input at the same time.

**Comment by whhxp** [comment]
I use Platypus to optimize electric motors by using GetDP, a FEM solver. 
Now I run the FEM solver on a Cloud computing platform (QingCloud) in Hong Kong with 10 instances.
I just simply use the Cloud Platform's API to get the IP and port, then call Paramiko to send and receive files. I also have written a zeroMQ based resource allocator in Python to prevent deadlock.

**Comment by khoopes** [comment]
I have followed the pattern here ant it seems to work very well:

https://github.com/Project-Platypus/Platypus/blob/87e744e09618bda46ee80f0e117337b6e582c588/examples/simple_parallel.py

it is limited in that it can only execute on the local machine platypus is running. At least I think so. Someone correct me if I am wrong as that would be amazing if it could somehow connect to remote hosts to execute.

**Comment by dhadka** [comment]
Hi @khoopes, that example uses the ProcessPoolEvaluator which only distributes the work locally.  To use remote hosts, you would first need to find a distributed computing library that supports remote hosts (e.g., see https://wiki.python.org/moin/ParallelProcessing) and setup the remote nodes.

Ideally, the library chosen supports one of the submission patterns supported by one of Platypus' evaluators.  For example, MapEvaluator takes a map-like function as an argument and will call that map function to distribute the evaluations.  You could use the Python [map](https://docs.python.org/3/library/functions.html#map) function, `concurrent.futures` [map](https://docs.python.org/3/library/concurrent.futures.html), or another map-like function provided by a third-party library.  We also have `SubmitEvaluator`, `ApplyEvaluator`, and `PoolEvaluator` that support other patterns.

As an example, https://github.com/Project-Platypus/Platypus/blob/87e744e09618bda46ee80f0e117337b6e582c588/examples/simple_mpi.py demonstrates using PoolEvaluator with a pool object provided by mpi4py.

**Comment by khoopes** [comment]
@dhadka, Thank you for your reply. I will look into using a distributed library. That could really speed up the project I am working on.

**Comment by human144** [comment]
Hi everyone, I would like to use the optimization tool box for a similar purpose. Hence, I am also looking into doing the objective evaluation in parallel. The simple_mpi.py script seems to work fine (also with my own model). However, independent of the number of cores that I use, the result history seems incomplete. As in, if I evaluate len(algorithm.result) is about the population_size, but not the total number of objective evaluations. 

Am I missing something here?
