### ISSUE TITLE
[Feature] Add a simvalid option

### ISSUE THREAD

**Issue by nelinnemann** [Project-Platypus/Platypus#74]
Using long running simulations they sometime fail or produce non-valid results.
It would be good to have so the objective function has an extra output so if the simulation is non-valid it is not used or discarded from the solution database.

So for a 2 objective simulation return [True/False, obj1, obj2] that way the first entry is always a check to use or discard the result.

**Comment by blooop** [comment]
I don't know if this is correct, but couldn't you use the constraints feature to achieve this?  If your simulation fails, you return that the constraint has failed.
