### ISSUE TITLE
Constrained problem

### ISSUE THREAD

**Issue by VP59m** [Project-Platypus/Platypus#76]
Hello everybody,
I'm using Platypus in an aerodynamic optimization problem.
I have some constraints in my problem, for example I'd like that my fitness function to be reduced by 5% compared to a reference value. So in my NSGAII problem I filter out infeasible solutions in this way: `feasible_solutions = [s for s in unique(nondominated(algorithm.result)) if s.feasible]`
I don't know what I'm doing wrong but in feasible_solutions list I find somentimes infeasible solution. What happens? Any ideas? I use Platypus as a black box so I'm sure I'm doing something wrong, but what?

regards Igor

**Comment by PastelBelem8** [comment]
Hey! Have you managed to address this problem?
