### ISSUE TITLE
How to change the population size, max number of generations, crossover and mutation probability for NSGAII?

### ISSUE THREAD

**Issue by shahryaramd** [Project-Platypus/Platypus#79]
How can I change the population size, max number of generations, crossover and mutation probability for NSGAII?

**Comment by dhadka** [comment]
You'd need to do something like the following:

    algorithm = NSGAII(problem, population_size=50, variator=GAOperator(SBX(0.95, 20.0), PM(2, 25.0)))
    algorithm.run(10000)

**Comment by shahryaramd** [comment]
In SBX and PM arguments, what do the 2 separate arguments mean?

**Comment by dhadka** [comment]
Details can be found in operators.py (e.g., https://github.com/Project-Platypus/Platypus/blob/723ad6763abff99b4f31305191b754c2c26867b0/platypus/operators.py#L81)

**Comment by shahryaramd** [comment]
Thanks.

**Comment by marijaivkovic** [comment]
What are the default values for the crossover and mutation probability for NSGAII used in Platypus?

**Comment by dhadka** [comment]
The default values for the operators can be found in `operators.py`, such as SBX:

https://github.com/Project-Platypus/Platypus/blob/723ad6763abff99b4f31305191b754c2c26867b0/platypus/operators.py#L125

and PM: 

https://github.com/Project-Platypus/Platypus/blob/723ad6763abff99b4f31305191b754c2c26867b0/platypus/operators.py#L81

**Comment by marijaivkovic** [comment]
Thank you

**Comment by harsha3080** [comment]
I understood mutation and crossover input but How can we give maximum number of generations in NSGA 2?

**Comment by mjalaliy** [comment]
You can control the max. number of generations with the number you provide in .run method of the algorithm object. That should be number_of_generation * population_size

**Comment by Erison356** [comment]
Hello! I just want to ask if "algorithm.run(100)" is also equivalent to the execution of the program with 100 generations. I can't see in the documentation where the indication for the number of generations made is in the program. Aside from the maximum number of generations, I need the data for the actual number of generations made. How could I know it? Thanks!

**Comment by dhadka** [comment]
@Erison356 `algorithm.run(100)` runs the program for 100 function evaluations (NFE).  For most algorithms, NFE = population_size * generations.  Thus, if you know the NFE and population size, you can get the number of generations.
