### ISSUE TITLE
Change value of parameters

### ISSUE THREAD

**Issue by lurbanrivero** [Project-Platypus/Platypus#8]
How can i change the value of parameters in any heuristic? For example in NSGAII change the crossover rate or mutation rate

**Comment by dhadka** [comment]
The `__init__` method for each algorithm class defines its customizable attributes.  For example, [NSGAII lets you provide an optional variator argument](https://github.com/Project-Platypus/Platypus/blob/master/platypus/algorithms.py#L157).  The variator's `__init__` method also has optional arguments for specifying crossover or mutation rates.  For example:

```python

NSGAII(...,
       variator = GAOperator(SBX(probability=0.75), PM(probability=0.05)))
```

**Comment by shahryaramd** [comment]
How to change its population size, max number of generations?
