### ISSUE TITLE
Population hybrid encoding

### ISSUE THREAD

**Issue by AngryCai** [Project-Platypus/Platypus#9]
I wonder whether the Platypus support hybrid encoding for decision variables? For example encode simultaneously with Real and Binary.

**Comment by dhadka** [comment]
Hi, it can support mixed types, but you (the developer) are responsible for creating the variation operator appropriate for the mixed type.  All of the operators are type-safe, meaning they only modify the decision variables of the appropriate type.

See for example the [CustomMutation](https://github.com/Project-Platypus/Platypus/blob/master/platypus/operators.py#L192) operator, which can be used to apply multiple mutation operators: `CustomMutation(PM(), BitFlip())`.

**Comment by mariocastrogama** [comment]
Hello, it is my impression or this seems also related to Issue #31
